# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: Check for trailing whitespace (auto-fixes)
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Python imports (auto-fixes)
        types: [ cython, pyi, python ]
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: Consistent Python code formatting (auto-fixes)
        language: python
        language_version: python3 # Should be a command that runs python3.6+
        args: [--line-length=100]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Enforcing style consistency across Python projects with flake8
        entry: flake8
        language: python
        types: [python]
        additional_dependencies:
          - flake8-broken-line
          - flake8-blind-except
          - flake8-builtins
          - flake8-logging-format
          - flake8-print
        # ignore W503, E203: conflict with black
        args: ['--max-line-length=100','--ignore=W503,E203,T001','--max-complexity=10']
